### ISSUE TITLE
FadeChangeHandler quick back navigation causes non-default alpha view state

### ISSUE THREAD

**Issue by chris6647** [bluelinelabs/Conductor#205]
Hello!
I encountered this issue in the app I am currently developing on, but I am able to reproduce the it in the demo app:
When pressing the "ViewPager" entry in the list, and then quickly pressing the back button, you are brought to the list, but if the timing is right, the view will appear faded (my guess is with a non-full alpha value). It seems as if stopping the transition quickly, does not let the AnimatorChangeHandler restore the first view correctly.
I tried the demo app checked out from a few Conductor tags, and was not able to reproduce it on version 2.0.1, had a crash in 2.0.2, and have the fade issue described above in 2.0.3 and then i skipped till 2.0.6 to confirm it was still an issue with the current version.

2.0.2 crash logs which may point in the right direction:
`01-19 15:39:46.337 10536-10536/com.bluelinelabs.conductor.demo E/InputEventSender: Exception dispatching finished signal.
01-19 15:39:46.337 10536-10536/com.bluelinelabs.conductor.demo E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
01-19 15:39:46.402 10536-10536/com.bluelinelabs.conductor.demo E/MessageQueue-JNI: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.animation.Animator.removeListener(android.animation.Animator$AnimatorListener)' on a null object reference
                                                                                       at com.bluelinelabs.conductor.changehandler.AnimatorChangeHandler$2.onAnimationEnd(AnimatorChangeHandler.java:170)
                                                                                       at android.animation.AnimatorSet.cancel(AnimatorSet.java:341)
                                                                                       at com.bluelinelabs.conductor.changehandler.AnimatorChangeHandler.onAbortPush(AnimatorChangeHandler.java:67)
                                                                                       at com.bluelinelabs.conductor.ControllerChangeHandler.abortPush(ControllerChangeHandler.java:113)
                                                                                       at com.bluelinelabs.conductor.ControllerChangeHandler.executeChange(ControllerChangeHandler.java:129)
                                                                                       at com.bluelinelabs.conductor.Router.performControllerChange(Router.java:615)
                                                                                       at com.bluelinelabs.conductor.Router.performControllerChange(Router.java:603)
                                                                                       at com.bluelinelabs.conductor.Router.popController(Router.java:121)
                                                                                       at com.bluelinelabs.conductor.Router.popCurrentController(Router.java:96)
                                                                                       at com.bluelinelabs.conductor.Router.handleBack(Router.java:82)
                                                                                       at com.bluelinelabs.conductor.demo.MainActivity.onBackPressed(MainActivity.java:40)
                                                                                       at android.app.Activity.onKeyUp(Activity.java:2483)
                                                                                       at android.view.KeyEvent.dispatch(KeyEvent.java:2664)
                                                                                       at android.app.Activity.dispatchKeyEvent(Activity.java:2736)
                                                                                       at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:50)
                                                                                       at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:224)
                                                                                       at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:50)
                                                                                       at com.android.internal.policy.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2310)
                                                                                       at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4127)
                                                                                       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4089)
                                                                                       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                                       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
                                                                                       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
                                                                                       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3787)
                                                                                       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
                                                                                       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3844)
                                                                                       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                                       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
                                                                                       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
                                                                                       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
                                                                                       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                                       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
                                                                                       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
                                                                                       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3820)
                                                                                       at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:3981)
                                                                                       at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2253)
                                                                                       at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1874)
                                                                                       at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1865)
                                                                                       at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2230)
                                                                                       at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
                                                                                       at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                                       at android.os.MessageQueue.next(MessageQueue.java:323)
                                                                                       at android.os.Looper.loop(Looper.java:135)
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

Thanks a lot for an awesome library! Been using it with great pleasure and ease :)

**Comment by EricKuck** [comment]
Should be working correctly now in the latest snapshot if you want to try it out.

**Comment by chris6647** [comment]
Thanks for the swift reply! It didn't fix the issue, but made it worse though :( 
Calling .end() on the animation, just ensures that the alpha is always set to 0, as that is the end state of the animation. So repeating the steps above to reproduce the issue, now always leaves us with a blank white screen.
Playing around with the code, I made it work by removing your addition of animator.end() in complete(..), and adding a call to resetFromView(from) in onAnimationCancel(...).
I could make a small PR if you wish, but the reason why I refrain from doing so now, is that I currently don't have time to test it more thoroughly to ensure it doesn't cause other breakage. It doesnt feel like the right fix either, as the act of moving back to the controller, should cause the Fade animation to run again and leave it in the correct state instead of being stuck with alpha 0.

**Comment by EricKuck** [comment]
Sorry about that! What I'd done fixed a similar issue for a different change handler and I assumed it'd work for the fade handler as well. This should actually be fixed in the latest snapshot now.

**Comment by chris6647** [comment]
No worries - your most recent snapshot fixes the issue for me as well, thanks a lot!
