### ISSUE TITLE
StackOverflowError: ControllerHostedRouter.getTransactionIndexer(ControllerHostedRouter.java:241)

### ISSUE THREAD

**Issue by MkhytarMkhoian** [bluelinelabs/Conductor#444]
`Fatal Exception: java.lang.StackOverflowError: stack size 8MB
       at com.bluelinelabs.conductor.ControllerHostedRouter.getTransactionIndexer(ControllerHostedRouter.java:241)
       at com.bluelinelabs.conductor.ControllerHostedRouter.getTransactionIndexer(ControllerHostedRouter.java:241)
       at com.bluelinelabs.conductor.ControllerHostedRouter.getTransactionIndexer(ControllerHostedRouter.java:241)
       at com.bluelinelabs.conductor.ControllerHostedRouter.getTransactionIndexer(ControllerHostedRouter.java:241)
       at com.bluelinelabs.conductor.ControllerHostedRouter.getTransactionIndexer(ControllerHostedRouter.java:241)
       at com.bluelinelabs.conductor.ControllerHostedRouter.getTransactionIndexer(ControllerHostedRouter.java:241)
       at com.bluelinelabs.conductor.ControllerHostedRouter.getTransactionIndexer(ControllerHostedRouter.java:241)
       at com.bluelinelabs.conductor.ControllerHostedRouter.getTransactionIndexer(ControllerHostedRouter.java:241)
       at com.bluelinelabs.conductor.ControllerHostedRouter.getTransactionIndexer(ControllerHostedRouter.java:241)
       at com.bluelinelabs.conductor.ControllerHostedRouter.getTransactionIndexer(ControllerHostedRouter.java:241)
       at com.bluelinelabs.conductor.Router.getActivity(Router.java:801)
       at com.bluelinelabs.conductor.Router.getActivity(Router.java:792)
       at com.bluelinelabs.conductor.Router.popController(Router.java:137)
       at com.bluelinelabs.conductor.Router.popCurrentController(Router.java:119)
       at com.bluelinelabs.conductor.Router.handleBack(Router.java:97)
       at classifieds.yalla.shared.navigation.TabMenuNavigator.handleBack(TabMenuNavigator.kt:194)
       at classifieds.yalla.features.main.TabMenuController.onBackPressed(TabMenuController.kt:159)
       at classifieds.yalla.shared.activity.ConductorBaseActivity.onBackPressed(ConductorBaseActivity.kt:84)
       at android.app.Activity.onKeyUp(Activity.java:2807)
       at android.view.KeyEvent.dispatch(KeyEvent.java:2717)
       at android.app.Activity.dispatchKeyEvent(Activity.java:3115)
       at android.support.v7.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:534)
       at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:58)
       at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:316)
       at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:323)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4390)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4361)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3905)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3958)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3924)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4051)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3932)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4108)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3905)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3958)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3924)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3932)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3905)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3958)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3924)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4084)
       at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4252)
       at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2437)
       at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2001)
       at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1992)
       at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2414)
       at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:323)
       at android.os.Looper.loop(Looper.java:142)
       at android.app.ActivityThread.main(ActivityThread.java:6379)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)`

**Comment by chris6647** [comment]
https://github.com/bluelinelabs/Conductor/issues/245 and https://github.com/bluelinelabs/Conductor/issues/419 seem to be similar - anything in those issues that can help you?
Otherwise steps to reproduce or more information would be great :)

**Comment by MkhytarMkhoian** [comment]
@EricKuck  Why you `return this;` and going to recursion? I think you need throw exception in this case or handle in another way.



```
@Override @NonNull
    Router getRootRouter() {
        if (hostController != null && hostController.getRouter() != null) {
            return hostController.getRouter().getRootRouter();
        } else {
            return this;
        }
    }

    @Override @Nullable
    TransactionIndexer getTransactionIndexer() {
        return getRootRouter().getTransactionIndexer();
    }
```

**Comment by EricKuck** [comment]
`this` is being returned because it's the root router. That's what's supposed to happen. I don't see how this would cause the StackOverflowException. Like @chris6647 said, some steps to reproduce would be super helpful, as I've never been able to reproduce this one myself.

**Comment by MkhytarMkhoian** [comment]
Ok, in a case when `this` is the root router, but in a case when `this` doesn't have `hostController` you return `this` again. So I still think this case needs to be handled.

I don't have steps to reproduce. I have this logs in crashlytics. If I could reproduce it, I will fix that my own:)

**Comment by MkhytarMkhoian** [comment]
if you look at the logs you'll see that this happened when handle back pressed

**Comment by PaulWoitaschek** [comment]
Can you post how you overwrote onBackPressed?

**Comment by MkhytarMkhoian** [comment]
```
override fun onBackPressed() {
        if (conductorRouter.backstackSize == 0) {
            super.onBackPressed()

        } else {
            val controller = conductorRouter.backstack.last().controller()
            when (controller) {
                is BackButtonListener -> {
                    if (!controller.onBackPressed()) {
                        router.exit()
                    }
                }
                else -> super.onBackPressed()
            }
        }
    }
```

**Comment by MkhytarMkhoian** [comment]
I added check, not tested it in production
```
if (conductorRouter.backstackSize == 0 && !conductorRouter.hasHost()) {
            super.onBackPressed()
}
```

**Comment by dpatel44** [comment]
I am having the same issue. I was able to reproduce it by modifying one of the test in the repo.  

```java

@RunWith(RobolectricTestRunner.class)
@Config(manifest = Config.NONE)
public class StateSaveTests {

    private FakePager pager;
    private RouterPagerAdapter pagerAdapter;
    private ActivityController<Activity> activityController;
    private TestController controller;

    public void createActivityController(Bundle savedInstanceState) {
        activityController = Robolectric.buildActivity(Activity.class).create().start().resume();
        Router router = Conductor.attachRouter(activityController.get(), new FrameLayout(activityController.get()), savedInstanceState);
        controller = new TestController();
        router.setRoot(RouterTransaction.with(controller));

        Router childRouter = controller.getChildRouter(new FrameLayout(activityController.get()));
        Controller childController = new TestController();
        childRouter.setRoot(RouterTransaction.with(childController));

        pager = new FakePager(new FrameLayout(activityController.get()));
        pager.setOffscreenPageLimit(1);

        pagerAdapter = new RouterPagerAdapter(childController) {
            @Override
            public void configureRouter(@NonNull Router router, int position) {
                if (!router.hasRootController()) {
                    router.setRoot(RouterTransaction.with(new TestController()));
                }
            }

            @Override
            public int getCount() {
                return 20;
            }
        };

        pager.setAdapter(pagerAdapter);
    }

    @Before
    public void setup() {
        createActivityController(null);
    }

    @Test
    public void testHostControllerDestoryed() {
        FrameLayout container = new FrameLayout(activityController.get());
        pagerAdapter.instantiateItem(container, 1);
        activityController.destroy();
        pagerAdapter.instantiateItem(container, 1);
    }

}

**Comment by EricKuck** [comment]
@dpatel44 I don't think your test is reproducing the same thing. When I run it I just get an NPE because you're trying to create a ViewPager page after the host activity is destroyed. This is impossible in real life, so it's not really anything we need to worry about.

**Comment by MkhytarMkhoian** [comment]
@EricKuck it seems this check is working `conductorRouter.hasHost()`, but this bugs appearance in another place in `RouterPagerAdapter` and I also add this check in this place (not tested yet)

```
override fun configureRouter(router: Router, position: Int) {
        if (!router.hasRootController() && router.hasHost()) {
            when (position) {
                FIRST_ITEM_ID -> router.setRoot(RouterTransaction.with(SellerActiveAdsController.newInstance(userId)))
                SECOND_ITEM_ID -> router.setRoot(RouterTransaction.with(SellerSoldAdsController.newInstance(userId)))
            }
        }
    }
```

**Comment by MkhytarMkhoian** [comment]
This solution not works

```
override fun configureRouter(router: Router, position: Int) {
        if (!router.hasRootController() && router.hasHost()) {
            when (position) {
                FIRST_ITEM_ID -> router.setRoot(RouterTransaction.with(SellerActiveAdsController.newInstance(userId)))
                SECOND_ITEM_ID -> router.setRoot(RouterTransaction.with(SellerSoldAdsController.newInstance(userId)))
            }
        }
    }
```

**Comment by EricKuck** [comment]
I believe this was fixed a while ago in 926f7da. It's only in the snapshot build for now, but a 2.1.5 stable will be released soon.

**Comment by MkhytarMkhoian** [comment]
@EricKuck You fix already in my production code and this exception still appears. 

I have the idea if we save `TransactionIndexer` object in a static reference and just return it when needed. What do you think about it?
